### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by suoranxiu** [twni2016/OrganSegRSTN_PyTorch#3]
Raising error "RuntimeError: CUDA out of memory." when I run the training.py on my gtx1660 with 6 GB memory. I would appreciate it if you can give me some advice on the code of  training steps .

**Comment by twni2016** [comment]
Please use GPU with larger memory like 12GB. The batch size is 1, so the GPU memory cannot be reduced anymore.

**Comment by suoranxiu** [comment]
Thank you！



------------------ 原始邮件 ------------------
发件人: "Tianwei Ni"<notifications@github.com>; 
发送时间: 2019年5月6日(星期一) 中午1:27
收件人: "twni2016/OrganSegRSTN_PyTorch"<OrganSegRSTN_PyTorch@noreply.github.com>; 
抄送: "索冉修"<542663467@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [twni2016/OrganSegRSTN_PyTorch] RuntimeError: CUDA out of memory.(#3)




Please use GPU with larger memory like 12GB. The batch size is 1, so the GPU memory cannot be reduced anymore.
