### ISSUE TITLE
algorithm of post-processing

### ISSUE THREAD

**Issue by suoranxiu** [twni2016/OrganSegRSTN_PyTorch#4]
Could you tell me more about the algorithm of post-processing? I have no idea about how it works from codes. Thank you !

**Comment by twni2016** [comment]
Did you mean the post_processing function written in C?
https://github.com/twni2016/OrganSegRSTN_PyTorch/blob/aff23489b1f3006761e3270178adfcccb63d0de9/SWIG_fast_functions/fast_functions.cc#L4-L5
The function computes the components of the binary predicted volume, and returns the components with size larger than a threshold.

**Comment by suoranxiu** [comment]
thank you !




------------------ 原始邮件 ------------------
发件人: "Tianwei Ni"<notifications@github.com>;
发送时间: 2019年5月17日(星期五) 晚上9:52
收件人: "twni2016/OrganSegRSTN_PyTorch"<OrganSegRSTN_PyTorch@noreply.github.com>;
抄送: "索冉修"<542663467@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [twni2016/OrganSegRSTN_PyTorch] algorithm of post-processing (#4)




Did you mean the postprocessing function written in C?
 https://github.com/twni2016/OrganSegRSTN_PyTorch/blob/aff23489b1f3006761e3270178adfcccb63d0de9/SWIG_fast_functions/fast_functions.cc#L4-L5
 The function computes the components of the binary predicted volume, and return the components with size larger than a threshold.
