### ISSUE TITLE
Slice thickness is the input channels?

### ISSUE THREAD

**Issue by suoranxiu** [twni2016/OrganSegRSTN_PyTorch#5]
Apologizing for bothering you. I'm running this code on my own lymphoma datasets. And there are some problems when initializing parameters. 

`slice_thickness = 3`

Slice thickness is the input channels?

`class RSTN(nn.Module):
	def __init__(self, crop_margin=20, crop_prob=0.5,crop_sample_batch=1, n_class=3, TEST=None):`

"n_class" is the output channels of the model?

**Comment by twni2016** [comment]
Yes, `slice_thickness` and `n_class` should be the same number (here 3) because input and output channels should be the same.

**Comment by suoranxiu** [comment]
Thank you so much!
